<template>
  <div class="right-table text-white">
    <a-table
      :columns="columns"
      :data="dataSource"
      :pagination="false"
      :scroll="scroll"
    />
  </div>
</template>

<script lang="ts">
interface stateValue {
  columns?: any;
  dataSource?: any;
  scroll?:any
}
import { defineComponent, reactive, toRefs } from "vue";
export default defineComponent({
  name: "TableRight",

  setup(props, context) {
    const state: stateValue = reactive({
      columns: [
        {
          title: "名称",
          dataIndex: "name",
          width: 56,
          align: "center",
          ellipsis: true,
          tooltip: { position: "top" },
        },
        {
          title: "位置",
          dataIndex: "location",
          width: 56,
          align: "center",
          ellipsis: true,
          tooltip: { position: "top" },
        },
        {
          title: "路径",
          dataIndex: "way",
          width: 56,
          align: "center",
          ellipsis: true,
          tooltip: { position: "top" },
        },
        {
          title: "编号",
          dataIndex: "number",
          width: 56,
          align: "center",
          ellipsis: true,
          tooltip: { position: "top" },
        },
        {
          title: "描述",
          dataIndex: "description",
          width: 56,
          align: "center",
          ellipsis: true,
          tooltip: { position: "top" },
        },
        {
          title: "公里标",
          dataIndex: "kilometer",
          width: 56,
          align: "center",
          ellipsis: true,
          tooltip: { position: "top" },
        },
        {
          title: "类型",
          dataIndex: "type",
          width: 56,
          align: "center",
          ellipsis: true,
          tooltip: { position: "top" },
        },
        {
          title: "设备",
          dataIndex: "equipment",
          width: 56,
          align: "center",
          ellipsis: true,
          tooltip: { position: "top" },
        },
        {
          title: "测试1",
          dataIndex: "test1",
          width: 56,
          align: "center",
          ellipsis: true,
          tooltip: { position: "top" },
        },
        {
          title: "测试2",
          dataIndex: "test2",
          width: 56,
          align: "center",
          ellipsis: true,
          tooltip: { position: "top" },
        },
        {
          title: "测试3",
          dataIndex: "test3",
          width: 56,
          align: "center",
          ellipsis: true,
          tooltip: { position: "top" },
        },
        {
          title: "测试4",
          dataIndex: "test4",
          width: 56,
          align: "center",
          ellipsis: true,
          tooltip: { position: "top" },
        },
      ],

      dataSource: [
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },

        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
        {
          name: "N22-E",
          location: "3653.26.dasdasdasdasdas",
          way: "P23-EP...",
          number: "A1201",
          description: "",
          kilometer: "5279,063dasdasasdas",
          type: "道岔:P43",
          equipment: "信号机",
          test1: "测试1",
          test2: "测试2",
          test3: "测试3",
          test4: "测试4",
        },
      ],
      scroll: {
        y: 100,
      },
    });
    return {
      ...toRefs(state),
    };
  },
});
</script>

<style lang="less" scoped>
:deep(.arco-table-container) {
  border-top: none !important;
  border-bottom: 1px solid #000 !important;
}
:deep(.arco-table-header) {
  .arco-table-cell {
    padding: 0;
    height: 26px;
    line-height: 26px;
    background-color: #43434b;
    color: #fff;
  }
  .arco-table-th {
    border: none !important;
  }
}
:deep(.arco-table-body) {
  .arco-table-tr:nth-child(2n-1) {
    .arco-table-cell {
      padding: 0;
      font-size: 12px;
      height: 24px;
      line-height: 24px;
      background-color: #1c1d1e;
      color: #ddd;
      cursor: pointer;
    }
  }
  .arco-table-tr:nth-child(2n) {
    .arco-table-cell {
      padding: 0;
      font-size: 12px;
      height: 24px;
      line-height: 24px;
      background-color: #222225;
      color: #ddd;
      cursor: pointer;
    }
  }

  .arco-table-td {
    border: none;
  }
  .arco-table-tr:hover {
    .arco-table-cell {
      box-sizing: border-box;
      border-top: 1px solid #c97a00;
      border-bottom: 1px solid #c97a00;
    }
  }
}
:deep(.arco-table-scroll-y::before) {
    height: 0;
    border: none;
}
:deep(.arco-table-header::-webkit-scrollbar) {
  width: 0;
}
:deep(.arco-table-body::-webkit-scrollbar) {
  width: 5px;
  height: 5px;
  background-color: #2e2e33;
}
:deep(.arco-table-body::-webkit-scrollbar-thumb) {
  background-color: #52525e;
}
// :deep(.arco-table-header::-webkit-scrollbar-thumb) {
//   width: 5px;
//   background-color: #2e2e33;
// }
</style>
